# Módulo 07, Tarefa 01

Vamos começar a mexer na nossa base de projeto? Já fizemos um exercício de montar a variável resposta, já pudemos perceber que essa atividade pode não ser trivial. Vamos agora trabalhar a base para que fique propícia ao *scikitlearn* para trabalharmos.

Lembrando, a base se chama demo01.csv, e originalmente está publicada [aqui](https://www.kaggle.com/rikdifos/credit-card-approval-prediction).

#### 1) Carregue a base e avalie:

- As variáveis
- Tipos de dados de cada variável
- Quantidade de missings
- Distribuição da variável resposta (mau)

In [ ]:
# 0)
import numpy as np
import seaborn as sns
import pandas as pd

# 1.1)
df = pd.read_csv('demo01.csv')
df.head()

,sexo,posse_de_veiculo,posse_de_imovel,qtd_filhos,tipo_renda,educacao,estado_civil,tipo_residencia,idade,tempo_emprego,possui_celular,possui_fone_comercial,possui_fone,possui_email,qt_pessoas_residencia,mau
0,M,Y,Y,0,Working,Secondary / secondary special,Married,House / apartment,58.832877,3.106849,1,0,0,0,2.0,False
1,F,N,Y,0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,52.356164,8.358904,1,0,1,1,1.0,False
2,F,N,Y,0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,52.356164,8.358904,1,0,1,1,1.0,False
3,M,Y,Y,0,Working,Higher education,Married,House / apartment,46.224658,2.106849,1,1,1,1,2.0,False
4,F,Y,N,0,Working,Incomplete higher,Married,House / apartment,29.230137,3.021918,1,0,0,0,2.0,False

In [ ]:
# 1.2)
print(df.info(),'\n\n')
print('Null:\n',df.isnull().sum(),'\n\n')
print('value_counts:\n',df['mau'].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16650 entries, 0 to 16649
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sexo                   16650 non-null  object
 1   posse_de_veiculo       16650 non-null  object
 2   posse_de_imovel        16650 non-null  object
 3   qtd_filhos             16650 non-null  int64
 4   tipo_renda             16650 non-null  object
 5   educacao               16650 non-null  object
 6   estado_civil           16650 non-null  object
 7   tipo_residencia        16650 non-null  object
 8   idade                  16650 non-null  float64
 9   tempo_emprego          16650 non-null  float64
 10  possui_celular         16650 non-null  int64
 11  possui_fone_comercial  16650 non-null  int64
 12  possui_fone            16650 non-null  int64
 13  possui_email           16650 non-null  int64
 14  qt_pessoas_residencia  16650 non-null  float64
 15  mau                    16650 non-null  bool
dtypes: bool(1), float64(3), int64(5), object(7)
memory usage: 1.9+ MB
None


Null:
 sexo                     0
posse_de_veiculo         0
posse_de_imovel          0
qtd_filhos               0
tipo_renda               0
educacao                 0
estado_civil             0
tipo_residencia          0
idade                    0
tempo_emprego            0
possui_celular           0
possui_fone_comercial    0
possui_fone              0
possui_email             0
qt_pessoas_residencia    0
mau                      0
dtype: int64


value_counts:
 mau
False    16260
True       390
Name: count, dtype: int64

#### 2) Vamos montar um metadados

1. Crie um dataframe com os nomes de cada variável e o tipo de dados de cada variável.
2. Adicione uma coluna nesse *dataframe* chamada "qtd_categorias" e coloque nela o número de categorias correspondente de cada variável.
    Dica:
        1. inicie uma lista vazia
        2. faça um for ao longo dos nomes das variáveis,
        3. conte o número de categorias dessa variável
        4. acumule essa informação de 3. na lista que você criou em 1.
        5. No final, essa lista pode ser atribuída à nossa variável.

In [ ]:
#2 )
nomes_variaveis = []
tipos_dados = []
qtd_categorias = []

# For

for coluna in df.columns:

    numero_de_categorias = df[coluna].nunique()

    nomes_variaveis.append(coluna)
    tipos_dados.append(df[coluna].dtype)
    qtd_categorias.append(numero_de_categorias)

# Dataframe

df_info = pd.DataFrame({
    'nome_variavel': nomes_variaveis,
    'tipo_dado': tipos_dados,
    'qtd_categorias': qtd_categorias
})


print(df_info)

            nome_variavel tipo_dado  qtd_categorias
0                    sexo    object               2
1        posse_de_veiculo    object               2
2         posse_de_imovel    object               2
3              qtd_filhos     int64               8
4              tipo_renda    object               5
5                educacao    object               5
6            estado_civil    object               5
7         tipo_residencia    object               6
8                   idade   float64            5298
9           tempo_emprego   float64            3005
10         possui_celular     int64               1
11  possui_fone_comercial     int64               2
12            possui_fone     int64               2
13           possui_email     int64               2
14  qt_pessoas_residencia   float64               9
15                    mau      bool               2

#### 3) Crie variáveis dummy para as variáveis necessárias (i.e. aquelas que são qualitativas e não estão armazenadas como {0, 1} ou {True, False}. Crie um *dataframe* apenas com as variáveis apropriadas para entrada no scikitlearn - elimine as variáveis tipo *str*, mantendo apenas suas versões *dummy*.

In [ ]:
colunas_qualitativas = ['sexo', 'posse_de_veiculo', 'posse_de_imovel', 'tipo_renda', 'educacao', 'estado_civil', 'tipo_residencia']

df_dummies = pd.get_dummies(df, columns=colunas_qualitativas, drop_first=True)


df_final = df_dummies

print(df_final.columns)
df_final.head()

Index(['qtd_filhos', 'idade', 'tempo_emprego', 'possui_celular',
       'possui_fone_comercial', 'possui_fone', 'possui_email',
       'qt_pessoas_residencia', 'mau', 'sexo_M', 'posse_de_veiculo_Y',
       'posse_de_imovel_Y', 'tipo_renda_Pensioner', 'tipo_renda_State servant',
       'tipo_renda_Student', 'tipo_renda_Working', 'educacao_Higher education',
       'educacao_Incomplete higher', 'educacao_Lower secondary',
       'educacao_Secondary / secondary special', 'estado_civil_Married',
       'estado_civil_Separated', 'estado_civil_Single / not married',
       'estado_civil_Widow', 'tipo_residencia_House / apartment',
       'tipo_residencia_Municipal apartment',
       'tipo_residencia_Office apartment', 'tipo_residencia_Rented apartment',
       'tipo_residencia_With parents'],
      dtype='object')

,qtd_filhos,idade,tempo_emprego,possui_celular,possui_fone_comercial,possui_fone,possui_email,qt_pessoas_residencia,mau,sexo_M,...,educacao_Secondary / secondary special,estado_civil_Married,estado_civil_Separated,estado_civil_Single / not married,estado_civil_Widow,tipo_residencia_House / apartment,tipo_residencia_Municipal apartment,tipo_residencia_Office apartment,tipo_residencia_Rented apartment,tipo_residencia_With parents
0,0,58.832877,3.106849,1,0,0,0,2.0,False,True,...,True,True,False,False,False,True,False,False,False,False
1,0,52.356164,8.358904,1,0,1,1,1.0,False,False,...,True,False,False,True,False,True,False,False,False,False
2,0,52.356164,8.358904,1,0,1,1,1.0,False,False,...,True,False,False,True,False,True,False,False,False,False
3,0,46.224658,2.106849,1,1,1,1,2.0,False,True,...,False,True,False,False,False,True,False,False,False,False
4,0,29.230137,3.021918,1,0,0,0,2.0,False,False,...,False,True,False,False,False,True,False,False,False,False

#### 4) Qual variável é mais poderosa?

Considere as variáveis ```possui_email``` e ```posse_de_veiculo```. Faça uma tabela cruzada entre elas e responda qual delas te parece mais poderosa para prever a probabilidade de ```mau = 1```?

In [ ]:
df_final['mau'] = df_final['mau'].astype(int)

# Criar tabelas cruzadas
crosstab_email = pd.crosstab(df_final['possui_email'], df_final['mau'], normalize='index')
crosstab_veiculo = pd.crosstab(df_final['posse_de_veiculo_Y'], df_final['mau'], normalize='index')

print("Tabela cruzada: possui_email:")
print(crosstab_email)

print("\nTabela cruzada: posse_de_veiculo:")
print(crosstab_veiculo)

Tabela cruzada: possui_email:
mau                  0         1
possui_email
0             0.976269  0.023731
1             0.979730  0.020270

Tabela cruzada: posse_de_veiculo:
mau                        0         1
posse_de_veiculo_Y
False               0.975732  0.024268
True                0.977905  0.022095

**Conclusão:**



*   Ambas aparentam ter o mesmo resultado similar, não sendo relevante a comparação entre as mesmas para a obtenção do resultado

#### 5) Salve a base, pois ela será utilizada no final deste módulo.

In [ ]:
df_final.to_csv('demo02.csv', index=False)

In [ ]:
'''
#Colab
from google.colab import files
files.download("demo02.csv")
'''

'\n#Colab\nfrom google.colab import files\nfiles.download("demo02.csv")\n'